Upgraded to Jekyll 3.8
m3xm/hikari-for-Jekyll pull request #47
Opened 2018-11-22 11:50 UTC by Kyrremann

Also removed pygments.rb as it is not supported on Github pages.

2018-11-22 18:59 UTC, ssorallen requested changes
Thanks a lot for this. Can you constrain your changes to just the Jekyll upgrade? Looks like this PR caught a lot of changes for your personal site.

2018-11-22 18:59 UTC, ssorallen commented on _config.yml
> +name: "kyrremann"
This PR contains a lot of change that look like they're personal and for your site. Can you put up a PR containing only the changes necessary to upgrade Jekyll?

2018-11-22 19:05 UTC, Kyrremann commented
Haha, that's a mistake from my side. I'll create a new pull request tonight.

2018-11-23 08:21 UTC, closed without merging

2018-11-23 08:23 UTC, Kyrremann commented
Created a new PR https://github.com/mx3m/hikari-for-jekyll/pull/48

If you are interested in the pygments fix, I can make a separated PR for that.